services:
  backend:
    container_name: backend
    build: ./backend/
    ports:
      - 1337:1337
    volumes:
      - ./backend:/app
      - /app/node_modules
    # command:
    #   - npm run develop
    tty: true
    restart: always
