# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: production-backend

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
  pull_request:
    branches: ["main"]
    paths:
      - "backend/**"
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [20.x, 21.x, 22.x]
  #   defaults:
  #     run:
  #       working-directory: ./backend
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: npm ci
  #     - run: npm run build

  deployment:
    runs-on: ["self-hosted", "Linux", "X64", "production-backend"]
    environment: production

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: clean up logs
        run: rm -f ~/.pm2/logs/*

      - name: Copy environment variables
        run: cp ~/actions-runner/_work/arablocalmarket/.env .env

      - name: Copy node_modules directory
        run: cp -r ~/actions-runner/_work/arablocalmarket/node_modules ~/actions-runner/_work/arablocalmarket/arablocalmarket/backend/

      # - run: npm i --production
      # - run: NODE_ENV=production npm run build
      # - run: NODE_ENV=production npx pm2 start server.js --name app # only for the first deployment

      - name: Start the app with pm2
        run: NODE_ENV=production npx pm2 restart app --cron-restart="0 23 * * *"
