# Use Node.js 20 LTS as the base image
FROM node:20

# Set the working directory inside the container
WORKDIR /app

# # Copy all sources code files 
COPY . .

# # Install dependencies
# RUN npm install

# # Expose the port your application runs on (change if needed)
# EXPOSE 3000

# Start the application
# CMD ["npm", "run",  "develop"]
# # or
# CMD ["node", "app.js"]
# # or
# Start with a shell
CMD ["bash"]

